"""empty message

Revision ID: 0f24d96806d5
Revises: 036ea666876a
Create Date: 2022-08-08 12:55:10.299207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f24d96806d5'
down_revision = '036ea666876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(), nullable=False))
    op.add_column('artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('desciption', sa.String(), nullable=True))
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('show', 'name')
    op.add_column('venue', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('venue', sa.Column('website_link', sa.String(), nullable=False))
    op.add_column('venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('desciption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'desciption')
    op.drop_column('venue', 'looking_for_talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'genre')
    op.add_column('show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    op.drop_column('artist', 'desciption')
    op.drop_column('artist', 'looking_for_venues')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
