"""empty message

Revision ID: 30189a55a170
Revises: 0f24d96806d5
Create Date: 2022-08-08 14:29:24.009224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30189a55a170'
down_revision = '0f24d96806d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('venue', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('venue', 'desciption')
    op.drop_column('venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('desciption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('venue', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('venue', 'description')
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
