"""empty message

Revision ID: d13583d53e6a
Revises: f4e29d291bf6
Create Date: 2022-08-09 16:02:38.147144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13583d53e6a'
down_revision = 'f4e29d291bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('artist', 'desciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('desciption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'description')
    # ### end Alembic commands ###
