"""empty message

Revision ID: f4e29d291bf6
Revises: 30189a55a170
Create Date: 2022-08-09 13:48:59.856521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e29d291bf6'
down_revision = '30189a55a170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=False))
    op.drop_column('venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
